name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Frontend
      uses: actions/checkout@v3
      with:
        repository: 'prathamesh0413/Amsa-website-FE'
        path: frontend

    - name: Checkout Backend
      uses: actions/checkout@v3
      with:
        repository: 'prathamesh0413/Amsa-website-BE'
        path: backend

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build Frontend
      working-directory: frontend
      run: |
        npm install
        npm run build   # build only, no export

    - name: Build Backend
      working-directory: backend
      run: npm install

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Clone Frontend and Backend repositories (if not cloned already)
          if [ ! -d "/home/ubuntu/Amsa-website-FE" ]; then
            git clone https://github.com/prathamesh0413/Amsa-website-FE.git /home/ubuntu/Amsa-website-FE
          fi

          if [ ! -d "/home/ubuntu/Amsa-website-BE" ]; then
            git clone https://github.com/prathamesh0413/Amsa-website-BE.git /home/ubuntu/Amsa-website-BE
          fi

          # Pull latest changes
          cd /home/ubuntu/Amsa-website-FE && git pull origin main
          cd /home/ubuntu/Amsa-website-BE && git pull origin main

          # Install Frontend deps & restart with PM2 (SSR mode on port 3000)
          cd /home/ubuntu/Amsa-website-FE
          npm install
          pm2 restart amsa-frontend || pm2 start "npm run start" --name amsa-frontend --watch

          # Install Backend deps & restart with PM2 (port 3001)
          cd /home/ubuntu/Amsa-website-BE
          npm install
          pm2 restart amsa-backend || pm2 start server.js --name amsa-backend --watch

          # Reload Nginx
          sudo systemctl reload nginx

          # Ensure everything is saved
          pm2 save
