name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Frontend
      uses: actions/checkout@v3
      with:
        repository: 'prathamesh0413/Amsa-website-FE'
        path: frontend

    - name: Checkout Backend
      uses: actions/checkout@v3
      with:
        repository: 'prathamesh0413/Amsa-website-BE'
        path: backend

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build Frontend
      working-directory: frontend
      run: |
        npm install
        npm run build
        # npm run export (if required for static export)

    - name: Build Backend
      working-directory: backend
      run: npm install

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Clone Frontend and Backend repositories (if not cloned already)
          if [ ! -d "/home/ubuntu/Amsa-website-FE" ]; then
            git clone https://github.com/prathamesh0413/Amsa-website-FE.git /home/ubuntu/Amsa-website-FE
          fi

          if [ ! -d "/home/ubuntu/Amsa-website-BE" ]; then
            git clone https://github.com/prathamesh0413/Amsa-website-BE.git /home/ubuntu/Amsa-website-BE
          fi

          # Pull latest changes for both repositories
          cd /home/ubuntu/Amsa-website-FE && git pull origin main
          cd /home/ubuntu/Amsa-website-BE && git pull origin main

          # Copy Frontend build output to Nginx directory (adjust path as needed)
          sudo rm -rf /var/www/html/*
          sudo cp -r /home/ubuntu/Amsa-website-FE/out/* /var/www/html/
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html

          # Install Backend Dependencies and Start Backend using PM2
          cd /home/ubuntu/Amsa-website-BE
          npm install
          pm2 restart amsa-backend || pm2 start server.js --name amsa-backend

          # Reload Nginx to serve frontend
          sudo systemctl reload nginx
          
          # Ensure Nginx and PM2 are running
          sudo systemctl restart nginx
          pm2 s
