name: CI/CD Deploy
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Frontend
        uses: actions/checkout@v3
        with:
          repository: 'prathamesh0413/Amsa-website-FE'
          path: frontend
 
      - name: Checkout Backend
        uses: actions/checkout@v3
        with:
          repository: 'prathamesh0413/Amsa-website-BE'
          path: backend
 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
 
      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build
          npm run export || true
 
      - name: Build Backend
        working-directory: backend
        run: npm install
 
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # --- System setup ---
            sudo apt update && sudo apt upgrade -y
            sudo apt install -y git nginx curl
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g pm2 serve
 
            # --- Clone repos if not present ---
            if [ ! -d "/home/ubuntu/Amsa-website-FE" ]; then
              git clone https://github.com/prathamesh0413/Amsa-website-FE.git /home/ubuntu/Amsa-website-FE
            fi
            if [ ! -d "/home/ubuntu/Amsa-website-BE" ]; then
              git clone https://github.com/prathamesh0413/Amsa-website-BE.git /home/ubuntu/Amsa-website-BE
            fi
 
            # --- Pull latest code ---
            cd /home/ubuntu/Amsa-website-FE && git pull origin main
            cd /home/ubuntu/Amsa-website-BE && git pull origin main
 
            # --- Frontend build and deploy ---
            cd /home/ubuntu/Amsa-website-FE
            npm install
            npm run build
            npm run export || true
            sudo rm -rf /var/www/amsa-fe
            sudo mkdir -p /var/www/amsa-fe
            sudo cp -r out/* /var/www/amsa-fe/
 
            # --- Backend setup ---
            cd /home/ubuntu/Amsa-website-BE
            npm install
            pm2 restart amsa-backend || pm2 start server.js --name amsa-backend --watch
            pm2 save
 
            # --- Nginx config (safe & idempotent) ---
            cat > /tmp/amsa_nginx.conf <<'NGINX'
server {
    listen 80;
    server_name _;
 
    root /var/www/amsa-fe;
    index index.html;
 
    location / {
        try_files $uri /index.html;
    }
 
    location /api {
        proxy_pass http://localhost:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
NGINX
 
            sudo mv /tmp/amsa_nginx.conf /etc/nginx/sites-available/amsa
            sudo ln -sf /etc/nginx/sites-available/amsa /etc/nginx/sites-enabled/amsa
            sudo rm -f /etc/nginx/sites-enabled/default
 
            # --- Validate and reload ---
            sudo nginx -t && sudo systemctl reload nginx
